name: Release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  push:
    branches:
      - test
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      # print cpu, ram & gpu info
      - name: Print CPU, RAM & GPU info
        run: lscpu