name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Test multiline output
        run: |
          for alias in $(echo ${{ env.ALIASES }} | tr "," "\n"); do
            echo domain: $alias
          done
      # RELEASE ACTION
      # - uses: actions/checkout@v2
      # - run: npm i -g pnpm
      # - run: pnpx zardoy-release empty --skip-github --output-file release.json
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   id: releaseInfo
      # # - run: mkdir assets
      # # - id: read_file
      # #   run: |
      # #     file_contents=$(cat test.json)
      # #     echo "::set-output name=file_contents::$file_contents"
      # # - run: |
      # #     jobjson=$(echo "${{ toJson(fromJson(steps.read_file.outputs.file_contents)) }}" )
      # #     echo $jobjson | yq
      # - run: cat release.json
