name: Release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  push:
    branches:
      - test
jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
      - run: cat /etc/os-release
