name: Release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g pnpm
      - run: pnpx zardoy-release empty --no-github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: release
      - run: echo '${{ toJson(steps.release.outputs) }}' > release.json
      # read release.json
      - run: cat release.json
