name: Release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  push:
    branches:
      - test
jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "zardoy/prismarine-web-client"
          ref: "next"
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm run build
