name: Release
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14
        - id: get-repos-1
          run: node -p "'::set-output name=repos::'+JSON.stringify(JSON.parse(require('fs').readFileSync('package.json', 'utf-8')).files)"
        - run: echo $OUTPUT
          env:
            OUTPUT: ${{ join(fromJSON(steps.get-repos-1.outputs.repos), '\n') }}
