name: Release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g pnpm
      - run: pnpx zardoy-release empty --skip-github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: releaseInfo
      - run: mkdir assets
      # read test.json into output
      - run: echo "file_contents=$(cat test.json)" >> $GITHUB_ENV
      - run: echo '${{ toJson(env.file_contents) }}'
      # - run: cat assets/release.json
