name: Release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  push:
    branches:
      - test
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mathiasvr/command-output
        with:
          run: echo "test"
        id: hello
      - run: echo "Said ${{ steps.hello.outputs.stdout }}"
