name: Release
on:
  push:
    branches: []
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Test multiline output
        run: |
          npm i -g pnpm tsx
          pnpm approve-builds canvas
          pnpm i canvas
          echo "const Canvas = require('canvas');const canvas = new Canvas(100, 100);canvas.toBuffer('image/png');" | tsx
      # RELEASE ACTION
      # - uses: actions/checkout@v2
      # - run: npm i -g pnpm
      # - run: pnpx zardoy-release empty --skip-github --output-file release.json
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   id: releaseInfo
      # # - run: mkdir assets
      # # - id: read_file
      # #   run: |
      # #     file_contents=$(cat test.json)
      # #     echo "::set-output name=file_contents::$file_contents"
      # # - run: |
      # #     jobjson=$(echo "${{ toJson(fromJson(steps.read_file.outputs.file_contents)) }}" )
      # #     echo $jobjson | yq
      # - run: cat release.json
