name: Release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g pnpm
      - run: pnpx zardoy-release empty --skip-github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: releaseInfo
      - run: mkdir assets
      - run: echo '{ "tag": "v0.1.8", "previousTag": "v0.1.7", "latestTag": "v0.1.8", "changelog": "\n\n## [vv0.1.8](releases/tag/vv0.1.8) - 2024-11-05\n<!-- bump-type:patch -->\n### Bug Fixes\n\n- test-change [`cc03d94`](/commit/cc03d94263e5ef6dfa64007af14683e908bcd6ee)\n- testing new github [`31488fe`](/commit/31488fe9b08125d8534be652ab1931c2ccbfab17)" }' > assets/release.json
      # - run: |
      #     echo "{\"test\": \"$(git rev-parse --short $GITHUB_SHA)\"}" > release.json
      - run: cat assets/release.json
