# on comment
name: Comment
on:
  issue_comment:
    types: [created]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # dump env
      - name: Dump GitHub env variables
        run: run node -e 'console.log(JSON.stringify(process.env))'
