# on comment
name: Comment
on:
  issue_comment:
    types: [created]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # dump env
      - name: Dump GitHub env variables
        env:
          GITHUB_ENV: ${{ toJson(env) }}
        run: echo "$GITHUB_ENV"
