name: Dump
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  pull_request:
jobs:
  release:
    
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event) }}
