name: Release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  workflow-dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: node -e 'console.log(JSON.stringify(process.env))'
