name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14
            # TODO install from action/direct url
            # TODO caching
        - run: npm i -g pnpm
        - run: pnpx -y zardoy-release testing
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
