name: Release
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - windows-latest
          - macos-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14
        - name: Cache pnpm modules
          uses: actions/cache@v2
          with:
            path: ~/.pnpm-store
            key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: latest
            run_install: |
              args: [--frozen-lockfile, --strict-peer-dependencies]
        - run: node -p "fs.readdirSync('.')"
