# on comment
name: PR dump data
on:
  pull_request_target:
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # dump env
      - name: Print PR number
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
